#!/usr/bin/env node
// Runs once per sessionStart to write a stable run.sh wrapper script.
// The wrapper lets command files call profile-handler.mjs via bash without
// knowing the plugin's install path at authoring time.
import { writeFileSync, mkdirSync, chmodSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const pluginRoot = process.env.COPILOT_PLUGIN_ROOT ?? '';
if (!pluginRoot) process.exit(0);

const dataDir = join(homedir(), '.copilot', 'plugin-data', 'skills-profile');
mkdirSync(dataDir, { recursive: true });

const handlerPath = join(pluginRoot, 'hooks', 'profile-handler.mjs');

const script = `#!/usr/bin/env bash
# Auto-generated by skills-profile plugin. Do not edit manually.
set -euo pipefail
HANDLER="${handlerPath}"
INPUT="$(printf '{"prompt":"/skills-profile %s"}' "$*")"
echo "$INPUT" | node "$HANDLER" | node -e "
  const raw = require('fs').readFileSync(0, 'utf8');
  try { process.stdout.write(JSON.parse(raw).responseContent ?? ''); }
  catch (e) { process.stdout.write(raw); }
"
`;

const scriptPath = join(dataDir, 'run.sh');
writeFileSync(scriptPath, script, 'utf8');
chmodSync(scriptPath, 0o755);
